### ISSUE TITLE
auto_instruments ignored files message cannot be disabled for rails console

### ISSUE THREAD

**Issue by klyonrad** [scoutapp/scout_apm_ruby#356]
following config

```yaml
  log_level: error
  auto_instruments: true
  auto_instruments_ignore: ['application_controller']
```

Then I enable autoloading and when I start the rails console I get dozens of [this message](https://github.com/scoutapp/scout_apm_ruby/blob/e3c19fa31bd5579db2e5533590f01846ef22a0e5/lib/scout_apm/auto_instrument/instruction_sequence.rb#L16) (we have a lot of application_controllers)

By the way, I don't think `warn` level is appropriate, this feels more liike an informational message
