### ISSUE TITLE
Stack Level Too Deep errors w/ new sentry-ruby gem 4.4.0

### ISSUE THREAD

**Issue by navied** [scoutapp/scout_apm_ruby#404]
Seems like a recent update to sentry gem is causing a bit of havoc with the scout gem see: https://github.com/getsentry/sentry-ruby/issues/1427

Would it be possible to do the required changes outlined above to make them behave properly?

Thanks!

**Comment by PikachuEXE** [comment]
For those who needs a quick workaround (without downgrading scout gems)
But disables `net/http` instrument
```yaml
# config/scout_apm.yml
common: &defaults
  disabled_instruments:
    - "NetHttp"

development:
  <<: *defaults

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults

production:
  <<: *defaults
```
